### ISSUE TITLE
0.6 Black Screen/ Hangs Indefinitely

### ISSUE THREAD

**Issue by 2UNIEK** [eldewritohelp/eldewritohelp.github.io#1]
I getting a black screen on launch since updating to 0.6. Previous versions did not have this issue, so I'm confused as to what the problem could be. I'm still using the same hardware from prior. 

Windows 7
i7-3820
GTX 970

**Comment by eldewritohelp** [comment]
This is for issues related to the help/FAQ page. 
Report game issues with specs to https://github.com/ElDewrito/ElDorito/issues if you cannot resolve them from the suggested methods on this page.
